### ISSUE TITLE
Add CLI flags to control what's converted

### ISSUE THREAD

**Issue by smoyer64** [junit-pioneer/convert-junit4-to-junit5#10]
- [ ] all
- [ ] imports
- [ ] Before/BeforeClass -> BeforeEach/BeforeAll

**Comment by boyarsky** [comment]
@smoyer64 I don't understand this one. If you convert the imports and not the asserts (or vice versa), the code doesn't compile.

**Comment by smoyer64** [comment]
@boyarsky Agreed ... I think everything should be a CLI option but with no flags a full conversion would take place.

And I'm sorry for flooding the project with issues ... these features came about as I tried (and mostly succeeded) in mass converting a pretty high-profile project.  Read the discussion on this PR for more background - https://github.com/apache/commons-lang/pull/353.  Unfortunately I've been promoting this projects and started writing these issues __before__ I read the comment you left in @StephenSeltzer 's issue about the project being somewhat abandoned.  Even with IntelliJ's support, I think there's a lot more that can be done with a dedicated tool and I think, with proper promotion that it would find a lot of use.

If you're not interested in continuing with the project would you consider donating it to the quasi-official JUnit Pioneer group (https://github.com/junit-pioneer)?  I'd be willing to take on most of this work and I think if fits pretty well.  We generally license under ASL 2.0 (since many of us are also Apache Software Foundation members but that's pretty compatible with the MIT license.

I had intended to send you and email yesterday but the day got away from me.  Hope you've been well the last year!

Steve

cc: @StephenSeltzer @nicolaiparlog

**Comment by boyarsky** [comment]
"Flooding with issues" is fine. It's good to have ideas. i implemented the two easiest ones. I'm glad that it helped you.

Realistically, I don't see myself having time to make any significant updates.  I wrote it for my use and didn't expect it to become popular :). And given that it already meets my needs, you can guess where it is on my priority list.

So yes, I think junit-pioneer would be a great home for it. Do you just fork it and I reference that? Or is there something I need to do to hand it over to junit-pioneer?

I picked the MIT license because it was the most permissive I could think of. I definitely have no problem with ASL 2.0.

**Comment by smoyer64** [comment]
Assuming @nicolaiparlog is okay with it, you can actually transfer the ownership via the "Settings" page (forked projects don't have issues - you can push to another repository in GitHub but then you sometimes end up with weird history).  It's in the __Danger Zone__ section towards the bottom.  We can add you and @StephenSeltzer to the team page and then you can still work on it if you want.  Assuming my faithful partner at Pioneer agrees, I also think it'd be good if you changed the license before transferring ownership just so that the intention is clear.

**Comment by boyarsky** [comment]
Sure. I'll wait until he can weigh in. 

I tried changing the license. Is ASL 2.0 the same as Apache 2.0)?

And thank you. It would be good to have access. Even if it isn't a priority for me, I know the code base well so I can still make small changes.

I look forward to seeing my project all grown up with a new package name :). I'm sure you'll ditch the "jb" and use a real one :).

**Comment by smoyer64** [comment]
Ouch ... package name is a sore subject over there.  We started with org.junit$pioneer (Nicolai thought it was cool - I was raging against the machine that didn't allow dashes in package names).  In any case, Apache 2.0 is correct.  And when it comes to OSS, the more the merrier!

**Comment by nicolaiparlog** [comment]
Hi, sorry to keep you waiting for so long. This is an interesting project and I think it fits well under the roof of JUnit Pioneer. :smiley:

@boyarsky If transferring the project is fine with you, then that would be the easiest way to preserve all issues and pull requests. I agree with @smoyer64 that it would be best to change the license first. Alternatively you could commit the license change after the transfer but in any event it should be you who makes this change. In case other people linked to this repo, you may want to add a new project under the same name with a simple README pointing to the new URL.

The project also needs a handy name. If you're up for it, @boyarsky, you're invited to dream one up. :wink: If you don't care, @smoyer64 and I can put our heads together.

Re package name: "Sore" puts it nicely. :sob: Once we have a project name, we can put it behind `org.junitpioneer.` and there we have the package name.

**Comment by smoyer64** [comment]
@nicolaiparlog We may want to consider org.junitpioneer.<project> as a package name.  I'm going to get back to upREST in the next couple weeks and had planned to do the same for that project (org.junitpioneer.uprest).

**Comment by nicolaiparlog** [comment]
That's what I meant. :smile:

**Comment by boyarsky** [comment]
@smoyer64 @nicolaiparlog I already changed the license. I tried transfering the repo to junit-pioneer and got "You don’t have the permission to create repositories on junit-pioneer". 

ps-= no preference on package name

**Comment by nicolaiparlog** [comment]
@boyarsky Oh right, permissions. Can you make me an admin (or what it's called) in this project, so I can transfer it to Pioneer?

> ps-= no preference on package name

Does that also mean you have no preference or idea for the project name? Personally, I would try to give it a catchier name, but if that's just me, we can leave it as-is.

**Comment by boyarsky** [comment]
I found where to give you push access. I don't know how to make a user an admin (I know how to do it in an org.)

So I'm moving the repo to your id and then you can move it to pioneers

**Comment by boyarsky** [comment]
Sent request to transfer to you and then you can transfer to pioneers.

Sorry, I'm not good at catchy names. Which is why I picked "convert-junit4-to-junit5" in the first place!

**Comment by nicolaiparlog** [comment]
Awesome, we're in business: https://github.com/junit-pioneer/convert-junit4-to-junit5 ! :tada: :+1:

By the way, weird to have all of this happening in a ticket for some CLI flags. :joy:

**Comment by boyarsky** [comment]
Excellent. And I created a new repo to link to this one. Thank you! Agreed on it being quite a discussion for some CLI flags. But the project is better off now and will enjoy it's new home.

**Comment by smoyer64** [comment]
It is weird ... I should have started a separate issue after the first aside.  Even worse, we still can't close this issue ;)

**Comment by signed** [comment]
Every project is slightly different in the way its structured and the tests are written.
We do not plan to provide command line arguments for all those nuances.
Therefore, the preferred way to use this tool is from source.
