### ISSUE TITLE
Provide a CLI input to allow the user to choose an assertion library

### ISSUE THREAD

**Issue by smoyer64** [junit-pioneer/convert-junit4-to-junit5#11]
- [ ] native JUnit5 assertions
- [ ] Hamcrest assertions
- [ ] AssertJ assertions

**Comment by signed** [comment]
Junit 4 assertions are converted to the matching assertions in Junit 5. 
Same for the build in assertThat that is shipped with Junit 4.

Are there other assertion migrations you are thinking of?

**Comment by signed** [comment]
I will close this for now. If you think there is work left let me know.
