### ISSUE TITLE
Provide a "linting" function

### ISSUE THREAD

**Issue by smoyer64** [junit-pioneer/convert-junit4-to-junit5#13]
This should flag classes that have incompatible imports/code (see https://github.com/junit-team/junit5/issues/1582).

**Comment by signed** [comment]
Migration of imports should be covered.
Are there still imports you think should be migrated?

The is infrastructure in place right now, to collect and report features that can not be automatically converted, have a look at `RunnerReporter`.  If you have concrete wishes for what should be reported  this should be easy to add now.

**Comment by signed** [comment]
Close for now. If you have a concrete example that should be supported please comment.
