### ISSUE TITLE
Complete move to JUnit Pioneer

### ISSUE THREAD

**Issue by nipafx** [junit-pioneer/convert-junit4-to-junit5#14]
Tasks:

* [ ] decide on project name (if we need a new one)
* [ ] rename GitHub project
* [ ] update documentation to new name
* [ ] rename all packages to `org.junitpioneer.$projectname`

It looks like GitHub forwards from https://github.com/boyarsky/convert-junit4-to-junit5 to here, so that's cool. Let's see whether the forward survives the project rename.

**Comment by boyarsky** [comment]
I created a new repo with the old name (which breaks the redirect, but avoids the problem of surviving the rename. It also makes it more obvious what happened!

**Comment by signed** [comment]
Is there still work left to complete the move?
