### ISSUE TITLE
Use org.junit.jupiter.api.Assertions package instead of org.junit.Assert

### ISSUE THREAD

**Issue by aqeelsmith** [junit-pioneer/convert-junit4-to-junit5#17]
Make use of org.junit.jupiter.api.Assertions package instead of org.junit.Assert
and also org.hamcrest.MatcherAssert.assertThat instead of org.junit.Assert.assertThat . 

I would like to help to make changes .

**Comment by signed** [comment]
Thank you for offering to help.
Support to convert `org.junit.Assert` and `org.junit.Assert.assertThat` was merged end of July.
- https://github.com/junit-pioneer/convert-junit4-to-junit5/blob/master/convert-junit4-to-junit5/src/main/java/jb/convert/ast/AssertConversion.java
- https://github.com/junit-pioneer/convert-junit4-to-junit5/blob/master/convert-junit4-to-junit5/src/main/java/jb/convert/ast/AssertThatConversion.java

Does this fit your needs?

**Comment by signed** [comment]
Please re-open in case you are missing features.
