### ISSUE TITLE
Rename test classes to **/*Tests.java per JUnit 5 convention

### ISSUE THREAD

**Issue by smoyer64** [junit-pioneer/convert-junit4-to-junit5#7]

**Comment by boyarsky** [comment]
If implemented, this would have to be an option. Some test classes call one another so a mass rename could easily break things.

**Comment by signed** [comment]
Personally I do not need this feature at the moment. Happy to review a PR.

**Comment by beatngu13** [comment]
Project/repository will be archived (see #59).
